#!/usr/bin/env python
import sys, os
if len(sys.argv) < 4:
    print "Usage: diffroot A.root B.root"
    print "Output plots are saved in \"plots\" directory"
    print "Options:"
    print "    -n : Normalize by area"
    os.exit()

if os.path.exists("plots"):
    print "plots directory already exists. Stop."
    os.exit()

from ROOT import *

f1 = TFile(sys.argv[1])
f2 = TFile(sys.argv[2])

if f1 == None or f2 == None:
    print "Cannot open root file"
    os.exit()

def getKeys(d):
    keys = []
    for key in [x.GetName() for x in d.GetListOfKeys()]:
        keys.append(d.GetName()+"/"+key)
        dau = d.GetDirectory(key)
        if dau != None: keys.expand(getKeys(dau))
    return keys

keys1 = set(getKeys(f1))
keys2 = set(getKeys(f2))

print "-"*40
print keys1
print "-"*40
print keys2

commonKeys = keys1.intersection(keys2)

print commonKeys

